/* This file was generated by SableCC (http://www.sablecc.org/). */

package lexAndParse.node;

import lexAndParse.analysis.*;

@SuppressWarnings("nls")
public final class AIntLitHexp extends PHexp
{
    private TIntLit _intLit_;

    public AIntLitHexp()
    {
        // Constructor
    }

    public AIntLitHexp(
        @SuppressWarnings("hiding") TIntLit _intLit_)
    {
        // Constructor
        setIntLit(_intLit_);

    }

    @Override
    public Object clone()
    {
        return new AIntLitHexp(
            cloneNode(this._intLit_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIntLitHexp(this);
    }

    public TIntLit getIntLit()
    {
        return this._intLit_;
    }

    public void setIntLit(TIntLit node)
    {
        if(this._intLit_ != null)
        {
            this._intLit_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._intLit_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._intLit_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._intLit_ == child)
        {
            this._intLit_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._intLit_ == oldChild)
        {
            setIntLit((TIntLit) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
