/* This file was generated by SableCC (http://www.sablecc.org/). */

package lexAndParse.node;

import lexAndParse.analysis.*;

@SuppressWarnings("nls")
public final class AIntArrType extends PType
{
    private TIntArr _intArr_;

    public AIntArrType()
    {
        // Constructor
    }

    public AIntArrType(
        @SuppressWarnings("hiding") TIntArr _intArr_)
    {
        // Constructor
        setIntArr(_intArr_);

    }

    @Override
    public Object clone()
    {
        return new AIntArrType(
            cloneNode(this._intArr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIntArrType(this);
    }

    public TIntArr getIntArr()
    {
        return this._intArr_;
    }

    public void setIntArr(TIntArr node)
    {
        if(this._intArr_ != null)
        {
            this._intArr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._intArr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._intArr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._intArr_ == child)
        {
            this._intArr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._intArr_ == oldChild)
        {
            setIntArr((TIntArr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
