/* This file was generated by SableCC (http://www.sablecc.org/). */

package lexAndParse.node;

import lexAndParse.analysis.*;

@SuppressWarnings("nls")
public final class ANegateExp extends PExp
{
    private TExl _exl_;
    private PExp _exp_;

    public ANegateExp()
    {
        // Constructor
    }

    public ANegateExp(
        @SuppressWarnings("hiding") TExl _exl_,
        @SuppressWarnings("hiding") PExp _exp_)
    {
        // Constructor
        setExl(_exl_);

        setExp(_exp_);

    }

    @Override
    public Object clone()
    {
        return new ANegateExp(
            cloneNode(this._exl_),
            cloneNode(this._exp_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANegateExp(this);
    }

    public TExl getExl()
    {
        return this._exl_;
    }

    public void setExl(TExl node)
    {
        if(this._exl_ != null)
        {
            this._exl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exl_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exl_)
            + toString(this._exp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exl_ == child)
        {
            this._exl_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exl_ == oldChild)
        {
            setExl((TExl) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
