/* This file was generated by SableCC (http://www.sablecc.org/). */

package lexAndParse.node;

import lexAndParse.analysis.*;

@SuppressWarnings("nls")
public final class TIntArr extends Token
{
    public TIntArr()
    {
        super.setText("int[]");
    }

    public TIntArr(int line, int pos)
    {
        super.setText("int[]");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TIntArr(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTIntArr(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TIntArr text.");
    }
}
