/* This file was generated by SableCC (http://www.sablecc.org/). */

package lexAndParse.node;

import lexAndParse.analysis.*;

@SuppressWarnings("nls")
public final class TSysout extends Token
{
    public TSysout()
    {
        super.setText("System.out.println");
    }

    public TSysout(int line, int pos)
    {
        super.setText("System.out.println");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSysout(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSysout(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSysout text.");
    }
}
